### ISSUE TITLE
Optional module for Guice compatibility

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-di#6]
Create an optional module to ease Guice transition. It doesn't have to work like Guice all the way, but perhaps can emulate Guice annotations, Module and Provider interfaces.

**Comment by stariy95** [comment]
Functional replacement of Guice is done. All tests are passed for all modules. 

Here is minor changes that are required to replace Guice for `guice-over-bootique-di` in all Bootique modules:
- `io.bootique.di.DIRuntimeException` is thrown instead of `com.google.inject.ProvisionException`
-  circular dependencies should be resolved manually (via `Provider`)
- `bootique-kotlin` module implements API that is not supported by this bridge (probably should be just removed)


Currently circular dependencies found in:

1. `bootique-jdbc-hikaricp-instrumented` module 
```
 Injection trace: 

 [0] resolving key <BindingKey: io.bootique.jdbc.DataSourceFactory>
    -> Get argument 0 for provider method 'createDataSource()' of module 'io.bootique.jdbc.JdbcModule'

 [1] resolving key <BindingKey: java.util.Map[java.lang.String, io.bootique.jdbc.managed.ManagedDataSourceStarter]>
    -> Invoking provider method 'provideDataSourceStarters()' of module 'io.bootique.jdbc.JdbcModule'

 [2] resolving key <BindingKey: io.bootique.jdbc.DataSourceFactory>
    -> Get argument 0 for provider method 'createDataSource()' of module 'io.bootique.jdbc.JdbcModule'
```
2. `bootique-job` module
```
Injection trace: 

 [0] resolving key <BindingKey: io.bootique.job.scheduler.Scheduler>
    -> Get argument 1 for provider method 'createScheduler()' of module 'io.bootique.job.runtime.JobModule'

 [1] resolving key <BindingKey: io.bootique.job.JobRegistry>
    -> Get argument 3 for provider method 'createJobRegistry()' of module 'io.bootique.job.runtime.JobModule'

 [2] resolving key <BindingKey: io.bootique.job.scheduler.Scheduler>
    -> Get argument 1 for provider method 'createScheduler()' of module 'io.bootique.job.runtime.JobModule'
```

**Comment by stariy95** [comment]
Circular dependencies resolved in modules. Exception thrown by DI is configurable.
